### ISSUE TITLE
'twitch.open' not found

### ISSUE THREAD

**Issue by Groot3** [kamerat/vs-code-twitch-chat#10]
https://i.imgur.com/oQxpcao.png // Command 'Twitch: Open chat' resulted in an error (command 'twitch.open' not found)
Issue persists through versions .0.0.5 to 0.0.6, does not happen in version .0.0.4.

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by kamerat** [comment]
Thank you for the heads up!
The issue was a package had removed a dependency, so we had to install it manually.
Should be fixed in 0.0.7 👍
