### ISSUE TITLE
How to set font size

### ISSUE THREAD

**Issue by aalemayhu** [kamerat/vs-code-twitch-chat#15]
Hei again,

could you expose the font size in the settings page? 

Did not find a way to increase it.

Thanks!

**Comment by kamerat** [comment]
ctrl + would do the trick, but this scales the whole vscode.
I added a simple setting to set font size for chat window alone in release [0.0.9](https://github.com/kamerat/vs-code-twitch-chat/releases/tag/0.0.9)
