### ISSUE TITLE
Please add support for custom emotes

### ISSUE THREAD

**Issue by aalemayhu** [kamerat/vs-code-twitch-chat#7]
Hei there!

Cool extension 😎  I would love to use this more on stream.
How can I get my custom emotes working here?

You can read more about user emotes here https://dev.twitch.tv/docs/v5/reference/users/#get-user-emotes

Thanks!

**Comment by aalemayhu** [comment]
Hei man,

hope you are doing well. Any update on this?

Thank you.

**Comment by kamerat** [comment]
Resolved in release 0[.0.9](https://github.com/kamerat/vs-code-twitch-chat/releases/tag/0.0.9).

However, custom emotes is only supported for the channel provided in the settings.
This means cross-channel emotes will not work.

I'm not really using this extension myself anymore, so feel free to send PR if there is something you would like to add in the future.
