### ISSUE TITLE
Twitch users w/o color

### ISSUE THREAD

**Issue by kamerat** [kamerat/vs-code-twitch-chat#8]
There is an issue regarding users not having color in the twitch-chat extension, but they do on Twitch. 
When I created this extension, I noticed some users had the color value returned from the Twitch API as being `null`.

I later discovered that this color is created on the Twitch client randomly if the said user has not selected one himself on Twitch. 
[[reference]](https://discuss.dev.twitch.tv/t/default-user-color-in-chat/385/12)

This statement might be somewhat confirmed if you see this clip from @aalemayhu - https://www.twitch.tv/videos/802717700?t=00h18m14s

Alemayhu states that the user is orange/yellow in his chat. If you see the recorded video, you will see in the chat that he is green, all the other people who's color is white(no color) is also green in the chat. 🤷‍♂️

In the reference above, someone comes with an example of adding color to the users from their name, this can be done in this extension too if wanted. I suppose even tho the color will no longer represent the same as on Twitch, it is at least better than white 👉 

I will leave this issue open for discussion in case more streamers nag regarding there being no colors 😏

**Comment by aalemayhu** [comment]
Can you also recreate this random colour behaviour like Twitch does it? I can send you a pull request or find someone in my community who wants to get started in open source.

Thanks!

- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: http://youtube.com/c/alexanderalemayhu <http://youtube.com/c/alexanderalemayhu>
Twitter: https://twitter.com/aalemayhu <https://twitter.com/aalemayhu>
Twitch: http://twitch.tv/alemayhu <http://twitch.tv/alemayhu>

**Comment by kamerat** [comment]
Yes @aalemayhu 😄 I just added this now. https://github.com/kamerat/vs-code-twitch-chat/commit/8dcb5c47f16f2c4758b40f4a2bda2772fcb88bfe

I will bundle up some bugfixes now before I release it tho.

> I can send you a pull request or find someone in my community who wants to get started in open source.
This is nice of you, I am always glad for PR's :) Regarding this exact issue, this is not needed 💯

**Comment by aalemayhu** [comment]
Thanks, look forward to trying it out 💟
